FROM node:18-alpine AS build

ARG VITE_BASE_URL
ENV VITE_BASE_URL ${VITE_BASE_URL}

WORKDIR /app
COPY ./frontend/package*.json ./
RUN npm install

COPY ./frontend/ .
#COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY ./frontend/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]